app: algorithms.cpp ../Library/FileIO.* ../Library/Sorting.*  ../Library/FileIO.h
	g++  algorithms.cpp ../Library/FileIO.cpp ../Library/Sorting.cpp  -o app 

run:
	./app

debug:
	lldb app

clean:
	rm -rf app*
